a = 56
b = 3
addition = a + b
multiplication = a * b
subtraction = a - b
division = a / b
modulus = a % b
exponential = a ** b
floor division = a // b
print("The value of", a, "+", b, "is =", addition)
print("The value of", a, "*", b, "is =", multiplication)
print("The value of", a, "-", b, "is =", subtraction)
print("The value of", a, "/", b, "is =", subtraction)
print("The value of", a, "%", b, "is =", modulus)
print("The value of", a, "**", b, "is =", exponential)
print("The value of", a, "//", b, "is =", floor division)