a = input("Enter a value: ")
b = input("Enter a value: ")
# sum = a + b
sum = (int(a) + int(b))
# print(sum)
subtract = (int(a) - int(b))
# print(subtract)
multiplication = (int(a) * int(b))
# print(multiplication)
divsion = (int(a) / int(b))
# print(division)
floor_diivision = (int(a) // int(b))
# print(floor_division)
exponential = (int(a) ** int(b))
print(exponential)